### ISSUE TITLE
Enhancement: This Needs a Column in "Numbers" Mod

### ISSUE THREAD

**Issue by maarxx** [Nibato/AutoExtractGenes#1]
Enhancement: This Needs a Column in "Numbers" Mod

It can just be a checkbox just like `Misc` -> `Self-tend`

https://steamcommunity.com/sharedfiles/filedetails/?id=1414302321

![selfTend](https://user-images.githubusercontent.com/7416299/225766161-c068ac9d-fedd-466c-a2a5-ed1a4f50335e.png)

**Comment by Nibato** [comment]
I've pushed this out to the steam workshop. Let me know if you have any issues. Thanks!

**Comment by maarxx** [comment]
Working great! Thanks so much! Great mod!
